#!/usr/bin/env bash

# shellcheck disable=SC2034

HANDLED_MODES=("cppcheck" "flake8" "pylint")

CPPCHECK_ERROR_THRESHOLD=25
CPPCHECK_NOTE_THRESHOLD=250
CPPCHECK_PERFORMANCE_THRESHOLD=25
CPPCHECK_PORTABILITY_THRESHOLD=25
CPPCHECK_STYLE_THRESHOLD=750
CPPCHECK_WARNING_THRESHOLD=50

PYLINT_CONVENTION_THRESHOLD=250
PYLINT_ERROR_THRESHOLD=250
PYLINT_FATAL_THRESHOLD=250
PYLINT_INFO_THRESHOLD=250
PYLINT_REFACTOR_THRESHOLD=250
PYLINT_WARNING_THRESHOLD=250

FLAKE8_COMPLEXITY_THRESHOLD=250
FLAKE8_ERROR_THRESHOLD=250
FLAKE8_FATAL_THRESHOLD=250
FLAKE8_WARNING_THRESHOLD=250
