---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
        args: ["--assume-in-merge"]
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-yaml
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: forbid-submodules
      - id: mixed-line-ending
        args: ["--fix=lf"]
        exclude: \.hex$
      - id: no-commit-to-branch
      - id: trailing-whitespace

  - repo: https://github.com/Lucas-C/pre-commit-hooks.git
    rev: v1.5.5
    hooks:
      - id: forbid-tabs
        exclude: (^|/)Kconfig(\..*)?$|(^|/).*\.gitconfig.*
      - id: remove-tabs
        exclude: (^|/)Kconfig(\..*)?$|(^|/).*\.gitconfig.*
