/* Native (native_sim) WAD storage backend.
 * The WAD is embedded as a C array (doom_wad / doom_wad_len, generated by
 * scripts/gen_wad_c.py). N_qspi_data_pointer(loc) returns &doom_wad[loc],
 * which is exactly what the engine expects from the XIP path. */

#include "n_qspi.h"

#include <stddef.h>
#include <stdint.h>
#include <string.h>

extern const unsigned char doom_wad[];
extern const unsigned int  doom_wad_len;

static const uint8_t *wad_base;

void N_qspi_init(void) {
    wad_base = (const uint8_t *)doom_wad;
}

void *N_qspi_data_pointer(size_t loc) {
    return (void *)(wad_base + loc);
}

void N_qspi_wait(void) {}

void N_qspi_read(size_t loc, void *buffer, size_t size) {
    memcpy(buffer, wad_base + loc, size);
}

void   N_qspi_erase_block(size_t loc) { (void)loc; }
void   N_qspi_write(size_t loc, void *buffer, size_t size) { (void)loc; (void)buffer; (void)size; }
void   N_qspi_write_block(size_t loc, void *buffer, size_t size) { (void)loc; (void)buffer; (void)size; }
void   N_qspi_reserve_blocks(size_t block_count) { (void)block_count; }
size_t N_qspi_alloc_block(void) { return 0; }
