---
name: Cppcheck verification
run-name: >
  ${{ github.workflow }} — Triggered by
  ${{ github.actor }} on ${{ github.ref_name }}

on:
  pull_request:
    paths:
      - 'zephyrdoom/**/*.c'
      - 'zephyrdoom/**/*.h'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  cppcheck-lint:
    name: Run Cppcheck verification
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare runner env for cppcheck tool
        run: |
          sudo apt-get update && sudo apt-get install -y \
          cppcheck

      - name: Run cppcheck command
        run: |
          cppcheck \
          --force \
          --language=c \
          --std=c89 \
          --platform=unix32 \
          --check-level=exhaustive \
          --enable=style \
          -I "${{ github.workspace }}/zephyrdoom/src/" \
          -I "${{ github.workspace }}/zephyrdoom/src/config/" \
          -I "${{ github.workspace }}/zephyrdoom/src/doom/" \
          "${{ github.workspace }}/zephyrdoom/src" \
          2>&1 | tee cppcheck-${{ github.run_number }}.log

      - name: Analyze cppcheck logs
        run: |
          "${{ github.workspace }}/.github/scripts/parse-cppcheck-logfile.sh" \
          cppcheck-${{ github.run_number }}.log

      - name: Upload cppcheck logs
        uses: actions/upload-artifact@v4
        with:
          name: cppcheck-${{ github.run_number }}
          path: |
            cppcheck-${{ github.run_number }}.log
            cppcheck-${{ github.run_number }}-summary.log
